Implement and save guestbook comments
shulijones/step-portfolio pull request #8
Opened 2020-06-29 21:22 UTC by shulijones

Walkthrough steps #5 and 6.

https://shulijones-step-2020.appspot.com/index.html

2020-06-29 21:50 UTC, kyracq approved these changes
LGTM!

2020-06-29 23:26 UTC, nsri-google submitted a review, later dismissed
Please make the suggested changes and submit again for review.

2020-06-29 23:57 UTC, nsri-google requested changes

2020-06-29 23:57 UTC, nsri-google commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +    //comments.add(comment);
A common software engineering "do not do" is to leave commented out code. Delete if you don't need this.

2020-06-29 23:57 UTC, nsri-google commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +    Gson gson = new Gson();
Do you need gson? It is not used anywhere.

2020-06-29 23:57 UTC, nsri-google commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +    //response.getWriter().println(gson.toJson(comments));
Delete commented out code.

2020-06-30 05:20 UTC, nsri-google approved these changes

2020-06-30 06:39 UTC, anicr7 approved these changes

2020-06-30 14:23 UTC, merged